### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by bokko-chan** [bokko-chan/furima-31049#9]
# URL
https://furima-31049.herokuapp.com/

# Basic認証
- ID: admin
- pasword: 2222

# 出品者用（ニックネームさん）
- ID: email@emai
- pasword: 11111a

# 購入者用（あだ名さん）
- ID: adana@adana
- pasword: 11111a

# 購入用カード
- 番号: 4242424242424242
- 期限: 12/24
- CVC: 123

**Comment by tech-taro** [comment]
bokko-chanさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
ユーザー管理機能の確認
・ユーザー本名は全角（漢字・ひらがな・カタカナ）で入力させること
→半角で入力して登録ができてしまったので、修正をお願い致します。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by bokko-chan** [comment]
ご確認ありがとうございます。
修正し本番環境で動作確認済みです。
宜しくお願い致します。

**Comment by tech-taro** [comment]
bokko-chanさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
商品編集機能の確認
・商品名やカテゴリーの情報など、すでに登録されている商品情報は編集画面を開いた時点で表示される
→編集画面を開くと「商品名」・「商品の説明」欄が空欄になっているので修正をお願いします。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by bokko-chan** [comment]
ご確認ありがとうございます。
修正致しました。宜しくお願い致します。

**Comment by tech-taro** [comment]
bokko-chanさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


必須ではありませんが、余裕があればこちらも修正し、よりクオリティの高いアプリケーションにしていただきたく存じます。（提出はしなくて大丈夫です。）
・商品削除機能の確認
→購入済み商品も削除できるように修正をお願いします。

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by bokko-chan** [comment]
ご確認、LGTMありがとうございます！
宜しくお願い致します。
